import random

print("Geben Sie die Länge des Codes ein")
laenge = input()

for _ in range(laenge):
    value = random.randint(0, 87)

    def numbers_to_strings(value):
        switcher = {
            0: char = 'A',
            1: char = 'B',
            2: char = 'C',
            3: char = 'D',
            4: char = 'E',
            5: char = 'F',
            6: char = 'G',
            7: char = 'H',
            8: char = 'I',
            9: char = 'J',
            10: char = 'K',
            11: char = 'L',
            12: char = 'M',
            13: char = 'N',
            14: char = 'O',
            15: char = 'P',
            16: char = 'Q',
            18: char = 'R',
            19: char = 'S',
            20: char = 'T',
            21: char = 'U',
            22: char = 'V',
            23: char = 'W',
            24: char = 'X',
            25: char = 'Y',
            26: char = 'Z',

            27: char = 'a',
            28: char = 'b',
            29: char = 'c',
            30: char = 'd',
            31: char = 'e',
            32: char = 'f',
            33: char = 'g',
            34: char = 'h',
            35: char = 'i',
            36: char = 'j',
            37: char = 'k',
            38: char = 'l',
            39: char = 'm',
            40: char = 'n',
            41: char = 'o',
            42: char = 'p',
            43: char = 'q',
            44: char = 'r',
            45: char = 's',
            46: char = 't',
            47: char = 'u',
            48: char = 'v',
            49: char = 'w',
            50: char = 'x',
            51: char = 'y',
            52: char = 'z',

            53: char = '0',
            54: char = '1',
            55: char = '2',
            56: char = '3',
            57: char = '4',
            58: char = '5',
            59: char = '6',
            60: char = '7',
            61: char = '8',
            62: char = '9',

            63: char = '+',
            64: char = '"',
            65: char = '*',
            66: char = 'ç',
            67: char = '%',
            68: char = '&',
            69: char = '/',
            70: char = '(',
            71: char = ')',
            72: char = '=',

            73: char = '@',
            74: char = '#',
            75: char = '¢',
            76: char = '$',
            77: char = '£',
            78: char = '[',
            79: char = ']',
            80: char = '{',
            81: char = '}',
            82: char = ',',
            83: char = ';',
            84: char = '.',
            85: char = ':',
            86: char = '-',
            87: char = '_',
        }
        return switcher.get(value, "nothing")
    password = password + char

print (password)
