import random

code = ''

print("Geben Sie die Länge des Codes ein")
laenge = int(input())

for _ in range(laenge):
    value = random.randint(0, 85)

    # big letters
    if value == 0: char = 'A'
    elif value == 1: char = 'B'
    elif value == 2: char = 'C'
    elif value == 3: char = 'D'
    elif value == 4: char = 'E'
    elif value == 5: char = 'F'
    elif value == 6: char = 'G'
    elif value == 7: char = 'H'
    elif value == 8: char = 'I'
    elif value == 9: char = 'J'
    elif value == 10: char = 'K'
    elif value == 11: char = 'L'
    elif value == 12: char = 'M'
    elif value == 13: char = 'N'
    elif value == 14: char = 'O'
    elif value == 15: char = 'P'
    elif value == 16: char = 'Q'
    elif value == 17: char = 'R'
    elif value == 18: char = 'S'
    elif value == 19: char = 'T'
    elif value == 20: char = 'U'
    elif value == 21: char = 'V'
    elif value == 22: char = 'W'
    elif value == 23: char = 'X'
    elif value == 24: char = 'Y'
    elif value == 25: char = 'Z'

    # small letters
    elif value == 26: char = 'a'
    elif value == 27: char = 'b'
    elif value == 28: char = 'c'
    elif value == 29: char = 'd'
    elif value == 30: char = 'e'
    elif value == 31: char = 'f'
    elif value == 32: char = 'g'
    elif value == 33: char = 'h'
    elif value == 34: char = 'i'
    elif value == 35: char = 'j'
    elif value == 36: char = 'k'
    elif value == 37: char = 'l'
    elif value == 38: char = 'm'
    elif value == 39: char = 'n'
    elif value == 40: char = 'o'
    elif value == 41: char = 'p'
    elif value == 42: char = 'q'
    elif value == 43: char = 'r'
    elif value == 44: char = 's'
    elif value == 45: char = 't'
    elif value == 46: char = 'u'
    elif value == 47: char = 'v'
    elif value == 48: char = 'w'
    elif value == 49: char = 'x'
    elif value == 50: char = 'y'
    elif value == 51: char = 'z'


    elif value == 52: char = '0'
    elif value == 53: char = '1'
    elif value == 54: char = '2'
    elif value == 55: char = '3'
    elif value == 56: char = '4'
    elif value == 57: char = '5'
    elif value == 58: char = '6'
    elif value == 59: char = '7'
    elif value == 60: char = '8'
    elif value == 61: char = '9'

    # special chars
    elif value == 62: char = '+'
    elif value == 63: char = '*'
    elif value == 64: char = '?'
    elif value == 65: char = '%'
    elif value == 66: char = '&'
    elif value == 67: char = '/'
    elif value == 68: char = '('
    elif value == 69: char = ')'
    elif value == 70: char = '='
    elif value == 71: char = '!'
    elif value == 72: char = '$'
    elif value == 73: char = '£'
    elif value == 74: char = '-'
    elif value == 75: char = '_'
    elif value == 76: char = ','
    elif value == 77: char = ';'
    elif value == 78: char = '.'
    elif value == 79: char = ':'
    elif value == 80: char = '['
    elif value == 81: char = ']'
    elif value == 82: char = '{'
    elif value == 83: char = '}'
    elif value == 84: char = '<'
    elif value == 85: char = '>'

    code += str(char)

print(code)
